### ISSUE TITLE
Driver not working with Cougar 700k

### ISSUE THREAD

**Issue by Nick-Lucas** [dmlambea/linux-cougar-500k-drv#3]
Hi Daniel,

So I'm sure this is user error but I've run out of ideas, and I'm hoping you can help (and then I can update the readme!).

So I've run across your driver through https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1511511 which I believe describes my problem. Basically my 700k stops working whenever I press a special key, like the split space-bar.

So I've been through the following steps without success:

* Installed this driver via the .deb package through the ubuntu GUI. Restarted, and still failing.
* Upgrade kernel to 4.20.17, restart. I then noticed that the [700k is only being picked up from 4.21 onward](https://patchwork.kernel.org/patch/10687969/) but I guess being on thisd kernel doesn't hurt?
* Installed driver via the .deb package with dpkg: `sudo dpkg -i hid-cougar-dkms_0.7.1_amd64.deb`. Restarted, and still failing.

The latter gives the following output, which seems to look okay:

```
nick@nick-desktop:~/Downloads$ sudo dpkg -i hid-cougar-dkms_0.7.1_amd64.deb 
[sudo] password for nick: 
(Reading database ... 188651 files and directories currently installed.)
Preparing to unpack hid-cougar-dkms_0.7.1_amd64.deb ...

-------- Uninstall Beginning --------
Module:  hid-cougar
Version: 0.7.1
Kernel:  4.20.17-042017-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

hid-cougar.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.20.17-042017-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


Running the post_remove script:
depmod...

Backing up initrd.img-4.20.17-042017-generic to /boot/initrd.img-4.20.17-042017-generic.old-dkms
Making new initrd.img-4.20.17-042017-generic
(If next boot fails, revert to initrd.img-4.20.17-042017-generic.old-dkms image)
update-initramfs.....

DKMS: uninstall completed.

------------------------------
Deleting module version: 0.7.1
completely from the DKMS tree.
------------------------------
Done.
Unpacking hid-cougar-dkms (0.7.1) over (0.7.1) ...
Setting up hid-cougar-dkms (0.7.1) ...
Loading new hid-cougar-0.7.1 DKMS files...
Building for 4.20.17-042017-generic
Building for architecture x86_64
Building initial module for 4.20.17-042017-generic
Done.

hid-cougar:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/4.20.17-042017-generic/updates/dkms/

Running the post_install script:

depmod...

Backing up initrd.img-4.20.17-042017-generic to /boot/initrd.img-4.20.17-042017-generic.old-dkms
Making new initrd.img-4.20.17-042017-generic
(If next boot fails, revert to initrd.img-4.20.17-042017-generic.old-dkms image)
update-initramfs.....

DKMS: install completed.

```

System specs at this point:

* Cougar 700k Keyboard
* Ubuntu 18.04, Desktop/GUI
* Kernel 4.20.17 installed via UKUU

Do you have any ideas on this?

**Comment by dmlambea** [comment]
Hi, Nick.

I sent the patch supporting model 700k to kernel.org only so this repo is lacking the vendor and device IDs for your keyboard. Please, give me some minutes and I'll make the changes here as well for your keyboard.

**Comment by dmlambea** [comment]
@Nick-Lucas, I've updated the repo. I don't have access to any model 700k right now to test the changes, but it should work. Please, give it a try.

**Comment by Nick-Lucas** [comment]
Thanks @dmlambea for the super fast help! Confirmed working after another `dpkg`. I'm assuming this driver mostly just stops the crash, as the windows key isn't working. But this is good enough for my needs :smile: 

I think your existing readme is fine since it was just another release required, but I've updated the issue title in case anyone else comes across this.

Nick
